FROM jupyter/datascience-notebook:latest

FROM continuumio/miniconda3:4.10.3

RUN apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    gawk \
    unzip \
    p7zip-full \
    git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN conda update conda
RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda update --all

RUN conda install --quiet --yes mamba  && conda clean --all

RUN mamba install -y pandas pyyaml openpyxl jinja2 scipy lxml html5lib matplotlib pytables pyreadstat tabulate zlib blosc fsspec numba pyarrow fastparquet gcsfs s3fs beautifulsoup4 bottleneck numexpr pyqt snakemake


# name your environment and choose python 3.x version
ARG conda_env=python36
ARG py_ver=3.6

# you can add additional libraries you want mamba to install by listing them below the first line and ending with "&& \"
RUN mamba create --quiet --yes -p "${CONDA_DIR}/envs/${conda_env}" python=${py_ver} ipython ipykernel && \
mamba clean --all -f -y

RUN conda update conda

RUN mamba install --yes \
    scanpy \
    anndata \
    anndata2ri \
    cellrank \
    rpy2 \
    r-argparse \
    pip \
    python-annoy \
    pypairs \
    numba \
    cython \
    joblib \
    pandas \
    scipy \
    matplotlib \
    scikit-learn \
    scikit-image \
    ipykernel \
    h5py \
    networkx \
    pytables \
    seaborn \
    cmake \
    statsmodels \
    python-igraph \
    louvain \
    leidenalg \
    bbknn \
    loompy \
    bioservices \
    r-essentials \
    r-rgl \
    r-seurat \
    r-loom \
    bioconductor-deseq2 \
    r-biocmanager

RUN mamba install --yes -c conda-forge jupyterlab

#RUN R -e "BiocManager::install('regioneR')"
#RUN R -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg38')"
#RUN git clone https://github.com/jvierstra/genome-tools
#RUN cd genome-tools
#RUN python setup.py install --user

#mamba clean -ai

#RUN pip install git+https://github.com/DmitryUlyanov/Multicore-TSNE.git
#RUN pip install git+https://github.com/theislab/diffxpy

#RUN pip install --quiet --no-cache-dir dask-labextension && \
#fix-permissions "${CONDA_DIR}" && \
#fix-permissions "/home/${NB_USER}" 

#RUN R -e "install.packages(c('sf', 'BiocManager', 'optparse', 'devtools', 'remotes', 'SMDTools', 'glue','miniUI'), repo='http://cran.rstudio.com/')"
#RUN R -e "BiocManager::install(c('patchwork', 'SingleCellExperiment', 'limma', 'enrichr'))"

